function task2
    y = dsolve ( ...
        'D2y + 5 * y = 2 * cos(sqrt (5) * t)', ...
        'y(0) = -1', 'Dy (0) = 1', ...
        't' ...
    );
    t = linspace (0, 50, 1000);
    plot(t, eval(y))
end